ALTER TABLE `fulfillment_record`
  MODIFY COLUMN `status` VARCHAR(32) NOT NULL
    COMMENT 'Fulfillment status: PENDING, PROCESSING, RETRY_PENDING, MANUAL_PENDING, SUCCEEDED, FAILED',
  ADD COLUMN `latest_attempt_id` VARCHAR(64) DEFAULT NULL
    COMMENT 'Latest attempt identifier, including non-active historical attempts'
    AFTER `current_attempt_id`,
  ADD COLUMN `processing_timeout_at` DATETIME(3) DEFAULT NULL
    COMMENT 'Timeout boundary of the current processing lease'
    AFTER `processing_started_at`,
  ADD COLUMN `retry_policy_json` JSON DEFAULT NULL
    COMMENT 'RetryPolicySnapshot for governance decisions'
    AFTER `last_diagnostic_trace_json`,
  ADD COLUMN `retry_state_json` JSON DEFAULT NULL
    COMMENT 'RetryState for governance decisions'
    AFTER `retry_policy_json`,
  ADD COLUMN `latest_failure_decision_json` JSON DEFAULT NULL
    COMMENT 'Latest FailureDecision generated by governance'
    AFTER `retry_state_json`;

UPDATE `fulfillment_record`
SET `latest_attempt_id` = `current_attempt_id`
WHERE `latest_attempt_id` IS NULL;

UPDATE `fulfillment_record`
SET `processing_timeout_at` = CASE
    WHEN `status` = 'PROCESSING' AND `processing_started_at` IS NOT NULL
      THEN DATE_ADD(`processing_started_at`, INTERVAL 15 MINUTE)
    ELSE NULL
  END
WHERE `processing_timeout_at` IS NULL;

UPDATE `fulfillment_record`
SET `retry_policy_json` = JSON_OBJECT(
  'fastRetryLimit', 1,
  'backoffRetryLimit', 2,
  'totalRetryBudget', 3,
  'backoffSchedule', JSON_ARRAY('PT5M', 'PT15M')
)
WHERE `retry_policy_json` IS NULL;

UPDATE `fulfillment_record`
SET `retry_state_json` = JSON_OBJECT(
  'fastRetryUsed', 0,
  'backoffRetryUsed', 0,
  'totalRetryUsed', 0,
  'budgetExhausted', FALSE
)
WHERE `retry_state_json` IS NULL;

ALTER TABLE `fulfillment_record`
  MODIFY COLUMN `retry_policy_json` JSON NOT NULL
    COMMENT 'RetryPolicySnapshot for governance decisions',
  MODIFY COLUMN `retry_state_json` JSON NOT NULL
    COMMENT 'RetryState for governance decisions';

ALTER TABLE `fulfillment_attempt_record`
  MODIFY COLUMN `status` VARCHAR(32) NOT NULL
    COMMENT 'Legacy attempt status retained for Stage A compatibility',
  ADD COLUMN `trigger` VARCHAR(48) DEFAULT NULL
    COMMENT 'Attempt trigger: INITIAL_EXECUTION, FAST_RETRY, BACKOFF_RETRY, PROCESSING_TIMEOUT_GOVERNANCE'
    AFTER `attempt_no`,
  ADD COLUMN `execution_status` VARCHAR(32) DEFAULT NULL
    COMMENT 'Execution status: STARTED, SUCCEEDED, FAILED_CLASSIFIED, ABANDONED'
    AFTER `trigger`,
  ADD COLUMN `failure_decision_json` JSON DEFAULT NULL
    COMMENT 'FailureDecision captured for governed failed attempts'
    AFTER `failure_json`,
  ADD COLUMN `provider_diagnostic_json` JSON DEFAULT NULL
    COMMENT 'Provider diagnostic observed while classifying a failure'
    AFTER `failure_decision_json`;

UPDATE `fulfillment_attempt_record`
SET `trigger` = 'INITIAL_EXECUTION'
WHERE `trigger` IS NULL;

UPDATE `fulfillment_attempt_record`
SET `execution_status` = CASE
    WHEN `status` = 'EXECUTING' THEN 'STARTED'
    WHEN `status` = 'SUCCEEDED' THEN 'SUCCEEDED'
    WHEN `status` = 'FAILED' THEN 'FAILED_CLASSIFIED'
    ELSE 'STARTED'
  END
WHERE `execution_status` IS NULL;

ALTER TABLE `fulfillment_attempt_record`
  MODIFY COLUMN `trigger` VARCHAR(48) NOT NULL
    COMMENT 'Attempt trigger: INITIAL_EXECUTION, FAST_RETRY, BACKOFF_RETRY, PROCESSING_TIMEOUT_GOVERNANCE',
  MODIFY COLUMN `execution_status` VARCHAR(32) NOT NULL
    COMMENT 'Execution status: STARTED, SUCCEEDED, FAILED_CLASSIFIED, ABANDONED';

CREATE TABLE `fulfillment_governance_audit_record` (
  `audit_id` VARCHAR(64) NOT NULL COMMENT 'Governance audit identifier',
  `fulfillment_id` VARCHAR(64) NOT NULL COMMENT 'Fulfillment identifier',
  `attempt_id` VARCHAR(64) DEFAULT NULL COMMENT 'Attempt identifier when the action is bound to an attempt',
  `action_type` VARCHAR(64) NOT NULL COMMENT 'Governance action type',
  `from_status` VARCHAR(32) DEFAULT NULL COMMENT 'Previous fulfillment status',
  `to_status` VARCHAR(32) DEFAULT NULL COMMENT 'Next fulfillment status',
  `failure_category` VARCHAR(64) DEFAULT NULL COMMENT 'Failure category associated with the action',
  `reason_code` VARCHAR(64) DEFAULT NULL COMMENT 'Stable governance reason code',
  `retry_budget_snapshot_json` JSON DEFAULT NULL COMMENT 'RetryState snapshot after the action',
  `actor_type` VARCHAR(16) NOT NULL COMMENT 'Actor type, fixed to SYSTEM in Stage B',
  `occurred_at` DATETIME(3) NOT NULL COMMENT 'Business time when the governance action occurred',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Record creation time',
  PRIMARY KEY (`audit_id`),
  KEY `idx_fulfillment_governance_audit_record_fulfillment_occurred_at` (`fulfillment_id`, `occurred_at`)
) COMMENT='Append-only governance audit records for fulfillment retry convergence';
